# Включаем загрузку конфигурации из Config Server
spring.config.import=optional:configserver:

# Имя приложения — по нему Config Server найдёт notification-service.properties
spring.application.name=notification-service

# Адрес Config Server
spring.cloud.config.uri=http://config-server:8888

# Завершать старт, если Config Server недоступен (рекомендуется)
spring.cloud.config.fail-fast=true

# Регистрация в Eureka (если используется Service Discovery)
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

# Если нужно, чтобы приложение падало при недоступности Config Server
spring.cloud.config.fail-fast=true